#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 300

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "mEMGx/aNGYM3"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

